package dillon.gameAPI.security;

/**
 * All of the sensitive actions in the API for monitoring.
 *
 * @author Dillon - Github dg092099.github.io
 * @since V1.13
 */
public enum RequestedAction {
	START_GAME, PAUSE, UNPAUSE, SETUP_GAME, SET_FULLSCREEN, CRASH_GAME, SHUTDOWN, SET_FPS, SET_BACKGROUND_COLOR, SET_BACKGROUND_IMAGE, INSTANTIATE_ENTITY, POST_EVENT, RECEIVE_EVENT, SHOW_GUI, HIDE_GUI, INSTANTIATE_MODS, ENABLE_DISCOVERY, DISABLE_DISCOVERY, CONNECT, DISCONNECT, START_NET_SERVER, STOP_NET_SERVER, MOVE_CAMERA, SET_TILESHEET, SET_LEVEL, PLAY_SOUND, EXECUTE_WITH_ENGINE, SCHEDULE_WAIT, SCHEDULE_REPEAT, CREATE_SECURITY_KEY, STOP_SOUND, RUN_SCRIPT
}
